services:
  python-app:
    build: .
    container_name: scheduler
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - TELEGRAM_BOT_URL=${TELEGRAM_BOT_URL}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    command: python main.py
    ports:
      - "8001:8001"
    networks:
      mynetwork:

networks:
  mynetwork:
    name: binance-network
    external: true