name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check that secrets are not empty
      run: |
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "❌ DOCKER_USERNAME is empty or missing"
          exit 1
        else
          echo "✅ DOCKER_USERNAME is set"
        fi

        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "❌ DOCKER_PASSWORD is empty or missing"
          exit 1
        else
          echo "✅ DOCKER_PASSWORD is set"
        fi


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: yourdockerhubusername/my-python-app:latest
